# Generated by Django 2.0.5 on 2018-10-10 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181004_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 10, 13, 21, 50, 22413)),
        ),
    ]
