# Generated by Django 2.0.5 on 2018-09-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('due_on', models.DateTimeField()),
                ('owner', models.CharField(max_length=255)),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
    ]
